"""new fields in user model

Revision ID: 959110273814
Revises: cf21d1eaca07
Create Date: 2019-08-19 17:30:44.431677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '959110273814'
down_revision = 'cf21d1eaca07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
